version: '3.8'

services:
  # =============================================================================
  # DATABASE
  # =============================================================================
  db:
    image: postgres:15-alpine
    container_name: biz-validator-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: business_validation
      POSTGRES_USER: bizuser
      POSTGRES_PASSWORD: bizpass123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bizuser -d business_validation"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - business-validation

  # =============================================================================
  # REDIS (for Django Celery)
  # =============================================================================
  redis:
    image: redis:7-alpine
    container_name: biz-validator-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - business-validation
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # =============================================================================
  # AI ENGINE (CrewAI FastAPI Service)
  # =============================================================================
  ai-engine:
    build:
      context: ./ai-engine
      dockerfile: Dockerfile
    container_name: biz-validator-ai
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql+asyncpg://bizuser:bizpass123@db:5432/business_validation
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
    volumes:
      - ./ai-engine/src:/app/src:ro
      - ai_output:/app/output
    depends_on:
      db:
        condition: service_healthy
    networks:
      - business-validation
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # =============================================================================
  # DJANGO WEB BACKEND
  # =============================================================================
  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: biz-validator-web
    restart: unless-stopped
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://bizuser:bizpass123@db:5432/business_validation
      - AGENTS_BASE_URL=http://ai-engine:8000
      - AGENT_CALLBACK_SECRET=secure-secret-key-123
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DJANGO_SECRET_KEY=django-secret-key-for-development
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      ai-engine:
        condition: service_healthy
    networks:
      - business-validation

  # =============================================================================
  # CELERY WORKER
  # =============================================================================
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: biz-validator-celery
    restart: unless-stopped
    command: celery -A project worker -l info
    environment:
      - DATABASE_URL=postgres://bizuser:bizpass123@db:5432/business_validation
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - AGENTS_BASE_URL=http://ai-engine:8000
      - AGENT_CALLBACK_SECRET=secure-secret-key-123
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - db
      - ai-engine
    networks:
      - business-validation

  # =============================================================================
  # CELERY BEAT (Scheduler)
  # =============================================================================
  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: biz-validator-beat
    restart: unless-stopped
    command: celery -A project beat -l info
    environment:
      - DATABASE_URL=postgres://bizuser:bizpass123@db:5432/business_validation
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - db
    networks:
      - business-validation

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  business-validation:
    driver: bridge
    name: business-validation-network

# =============================================================================
# VOLUMES
# =============================================================================
volumes:
  postgres_data:
    name: business-validation-postgres-data
    driver: local
  
  ai_output:
    name: business-validation-ai-output
    driver: local